# Generated by Django 5.2.1 on 2025-10-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
