# Generated by Django 5.2.1 on 2025-10-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0002_alter_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_date',
        ),
    ]
